---
title: "Python Error: ForkAwareLocal Multiprocessing"
date: 2023-02-11T23:43:22+07:00
draft: false
authors: ["hoangmnsd"]
categories: [Tech-Notes]
tags: [Python]
comments: true
toc: true
# below props are for the404blog theme
authorImg: "https://raw.githubusercontent.com/hoangmnsd/images-bucket/master/static/images/hoangmsnd-avatar001.jpg"
description: "L·ªói AttributeError: 'ForkAwareLocal' object has no attribute 'connection'"
---

L·ªói n√†y x·∫£y ra v·ªõi h√†m schedule-check-blog-comment-v3 c·ªßa m√¨nh, 

C√°i nguy hi·ªÉm c·ªßa n√≥ l√† thi tho·∫£ng m√≥i x·∫£y ra. L√∫c test th√¨ ngon l√†nh, n·∫øu ko monitor th∆∞·ªùng xuy√™n th√¨ s·∫Ω ko bi·∫øt c√≥ l·ªói

G·∫ßn ƒë√¢y check c√°i log monitoring c·ªßa Lambda m·ªõi th·∫•y t·ªâ l·ªá l·ªói kh√° nhi·ªÅu: (·∫£nh) trong 14 l·∫ßn ch·∫°y g·∫ßn nh·∫•t th√¨ l·ªói ƒë·∫øn 6 l·∫ßn

![](https://raw.githubusercontent.com/hoangmnsd/images-bucket/master/static/images/lambda-monitor-error-count.jpg)

Sau khi t√¨m xem log th√¨ th·∫•y l·ªói `AttributeError: 'ForkAwareLocal' object has no attribute 'connection'` n√†y:

```
2023-03-07T15:00:10.186+07:00    [INFO] 2023-03-07T08:00:10.186Z Current datetime: 2023-03-07 08:00:10.186406    
2023-03-07T15:00:10.209+07:00    START RequestId: 3bd7d8xxxxxd9xxx6b8d1 Version: $LATEST    
2023-03-07T15:00:21.933+07:00    Process Process-68:    
2023-03-07T15:00:22.214+07:00    Traceback (most recent call last):    
2023-03-07T15:00:22.214+07:00    File "/var/lang/lib/python3.9/multiprocessing/managers.py", line 802, in _callmethod    
2023-03-07T15:00:22.214+07:00    conn = self._tls.connection    
2023-03-07T15:00:22.215+07:00    AttributeError: 'ForkAwareLocal' object has no attribute 'connection'    
2023-03-07T15:00:22.215+07:00    During handling of the above exception, another exception occurred:    
2023-03-07T15:00:22.215+07:00    Traceback (most recent call last):    
2023-03-07T15:00:22.215+07:00    File "/var/lang/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap    
2023-03-07T15:00:22.215+07:00    self.run()    
2023-03-07T15:00:22.215+07:00    File "/var/lang/lib/python3.9/multiprocessing/process.py", line 108, in run    
2023-03-07T15:00:22.215+07:00    self._target(*self._args, **self._kwargs)    
2023-03-07T15:00:22.215+07:00    File "/var/task/lambda_function.py", line 104, in check_comment    
2023-03-07T15:00:22.215+07:00    cmt_total.append("yes")    
2023-03-07T15:00:22.215+07:00    File "<string>", line 2, in append    
2023-03-07T15:00:22.215+07:00    File "/var/lang/lib/python3.9/multiprocessing/managers.py", line 806, in _callmethod    
2023-03-07T15:00:22.215+07:00    self._connect()    
2023-03-07T15:00:22.215+07:00    File "/var/lang/lib/python3.9/multiprocessing/managers.py", line 793, in _connect    
2023-03-07T15:00:22.215+07:00    conn = self._Client(self._token.address, authkey=self._authkey)    
2023-03-07T15:00:22.215+07:00    File "/var/lang/lib/python3.9/multiprocessing/connection.py", line 507, in Client     
2023-03-07T15:00:22.215+07:00    c = SocketClient(address)    
2023-03-07T15:00:22.215+07:00    File "/var/lang/lib/python3.9/multiprocessing/connection.py", line 635, in SocketClient   
2023-03-07T15:00:22.215+07:00    s.connect(address)    
2023-03-07T15:00:22.215+07:00    ConnectionRefusedError: [Errno 111] Connection refused    
```

C√≥ v·∫ª link n√†y h·ªØu d·ª•ng: https://stackoverflow.com/questions/60049527/shutting-down-manager-error-attributeerror-forkawarelocal-object-has-no-attr

ƒê√∫ng l√† hi·ªán t·∫°i code x·ª≠ l√Ω ki·ªÉu d√πng chung nhi·ªÅu multiprocessing.Manager object nh∆∞ n√†y:  

```
# Prepair variables that use to share in multi-processing
manager = multiprocessing.Manager()
cmt_total = manager.list()
new_cmt = manager.list()
post_have_new_cmt = manager.list()

# r·ªìi b√™n d∆∞·ªõi ch·∫°y logic ki·ªÉu:
for div in comment_meta:
    new_cmt.append("xxx")
    cmt_total.append("xxx")
    post_have_new_cmt.append("xxx")
```

C·∫ßn ph·∫£i s·ª≠a l·∫°i nh∆∞ n√†y:  

```
# Prepair variables that use to share in multi-processing
cmt_total_manager = multiprocessing.Manager()
cmt_total = cmt_total_manager.list()

new_cmt_manager = multiprocessing.Manager()
new_cmt = new_cmt_manager.list()

post_have_new_cmt_manager = multiprocessing.Manager()
post_have_new_cmt = post_have_new_cmt_manager.list()

# r·ªìi b√™n d∆∞·ªõi ch·∫°y logic ki·ªÉu:
for div in comment_meta:
    new_cmt.append("xxx")
    cmt_total.append("xxx")
    post_have_new_cmt.append("xxx")
```

Th√¨ hi·ªán t·∫°i sau kho·∫£ng 2 tu·∫ßn th√¨ ko c√≥ t√Ω l·ªói `AttributeError: 'ForkAwareLocal' object has no attribute 'connection'` n√†o xu·∫•t hi·ªán n·ªØa. üòò

# CREDIT

https://stackoverflow.com/questions/60049527/shutting-down-manager-error-attributeerror-forkawarelocal-object-has-no-attr